### ISSUE TITLE
Always override custom options with entryPoints and outfile

### ISSUE THREAD

**Issue by pbadenski** [sod/cypress-esbuild-preprocessor#2]
It looks like at the moment entryPoints and outfile options required for the preprocessor to work can be accidentally overriden by custom esbuild options. Shouldn't these always be applied regardless of custom options?

Ie.

Is:
```
return build({
        entryPoints,
        outfile,
        // ....
        ...(options?.esbuildOptions ?? {}),
      })
```

Should be:
```
return build({
        // ....
        ...(options?.esbuildOptions ?? {}),
        entryPoints,
        outfile
      })
```

**Comment by sod** [comment]
You are right. I may swap them if I touch the code again for something else. But this seems not to be release worthy on its own.
