### ISSUE TITLE
Not working with newer version of cypress?

### ISSUE THREAD

**Issue by pbadenski** [sod/cypress-esbuild-preprocessor#3]
I'm getting this error for cypress 7.5.0: ```Error: It is required to register dev-server plugin that implements `dev-server:start` event for component testing.```

I'm correct in thinking this plugin needs changes to work for a newer version of cypress?

**Comment by sod** [comment]
We are on cypress 8.3 right now and it works. You may use a cypress feature I'm not aware of. Could you solve the problem?

**Comment by sod** [comment]
I couldn't reproduce it.
