### ISSUE TITLE
Code-coverage?

### ISSUE THREAD

**Issue by thednp** [sod/cypress-esbuild-preprocessor#4]
I've been working with most preprocesssors and so far only esbuild based work for me, IDK why, but that's that.

Do you happen to have any example with your plugin and `@cypress/code-coverage` working together?

Thank you.

**Comment by sod** [comment]
No, we don't use `@cypress/code-coverage`

**Comment by sod** [comment]
Seems like `@bahmutov/cypress-esbuild-preprocessor` has cascading transformer support out of the box. You could try suggestion https://stackoverflow.com/a/72896285, just add `@cypress/code-coverage` as another plugin in front or behind esbuild.
